"""initial schema

Revision ID: 3348e1f10213
Revises: 
Create Date: 2026-09-24 04:01:03.495032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '3348e1f10213'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('agent', sa.String(length=100), nullable=False),
    sa.Column('workshop', sa.Integer(), nullable=True),
    sa.Column('prompt_version', sa.String(length=30), nullable=True),
    sa.Column('input_snapshot', sa.String(length=64), nullable=True),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_analysis_id'), 'agent_runs', ['analysis_id'], unique=False)
    op.create_table('analyses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('si_description', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_workshop', sa.Integer(), nullable=False),
    sa.Column('threat_model', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('besoins', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('value', sa.String(length=20), nullable=True),
    sa.Column('supports', sa.String(length=500), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_analysis_id'), 'assets', ['analysis_id'], unique=False)
    op.create_table('feared_events',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('bien_essentiel_id', sa.Uuid(), nullable=True),
    sa.Column('besoin', sa.String(length=30), nullable=True),
    sa.Column('gravite', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feared_events_analysis_id'), 'feared_events', ['analysis_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_source'), 'knowledge_documents', ['source'], unique=False)
    op.create_table('risk_sources',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('objectif', sa.String(length=500), nullable=True),
    sa.Column('motivation', sa.String(length=500), nullable=True),
    sa.Column('capacite', sa.String(length=20), nullable=True),
    sa.Column('biens_vises', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('pertinence', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_sources_analysis_id'), 'risk_sources', ['analysis_id'], unique=False)
    op.create_table('risks',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=True),
    sa.Column('identifiant', sa.String(length=30), nullable=True),
    sa.Column('gravite', sa.String(length=20), nullable=True),
    sa.Column('vraisemblance', sa.String(length=20), nullable=True),
    sa.Column('niveau', sa.String(length=20), nullable=True),
    sa.Column('traitement', sa.String(length=20), nullable=True),
    sa.Column('mesures', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('risque_residuel', sa.String(length=20), nullable=True),
    sa.Column('sources', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('justification', sa.String(length=4000), nullable=True),
    sa.Column('valide_par', sa.String(length=255), nullable=True),
    sa.Column('validated_at', sa.String(length=50), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_analysis_id'), 'risks', ['analysis_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('identifiant', sa.String(length=30), nullable=True),
    sa.Column('source_risque_id', sa.Uuid(), nullable=True),
    sa.Column('evenement_redoute_id', sa.Uuid(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('gravite', sa.String(length=20), nullable=True),
    sa.Column('vraisemblance', sa.String(length=20), nullable=True),
    sa.Column('niveau', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_analysis_id'), 'scenarios', ['analysis_id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('workshops',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('validated_by', sa.String(length=255), nullable=True),
    sa.Column('validated_at', sa.String(length=50), nullable=True),
    sa.Column('corrections', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshops_analysis_id'), 'workshops', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_workshops_numero'), 'workshops', ['numero'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workshops_numero'), table_name='workshops')
    op.drop_index(op.f('ix_workshops_analysis_id'), table_name='workshops')
    op.drop_table('workshops')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scenarios_analysis_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_risks_analysis_id'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_risk_sources_analysis_id'), table_name='risk_sources')
    op.drop_table('risk_sources')
    op.drop_index(op.f('ix_knowledge_documents_source'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_feared_events_analysis_id'), table_name='feared_events')
    op.drop_table('feared_events')
    op.drop_index(op.f('ix_assets_analysis_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_agent_runs_analysis_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
