"""risk_source.activite

Revision ID: ccfb9f7d497d
Revises: 3348e1f10213
Create Date: 2026-09-24 06:44:09.747589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccfb9f7d497d'
down_revision: Union[str, None] = '3348e1f10213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_sources', sa.Column('activite', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_sources', 'activite')
    # ### end Alembic commands ###
